### ISSUE TITLE
Kallisto gene vs tcc counts

### ISSUE THREAD

**Issue by Rajesh-HKU** [pachterlab/gget_examples#6]
Dear team,
I compared the gene and the tcc count for the same dataset after running kallisto on a set of fastq files. I find big discrepancies between the two counts. The gene count =0 even when  the tcc counts >=1 in a vast majority of cases. I have only considered tcc counts where the equivalence class contains exactly one transcript corresponding to the gene. Can you please help me understand why this maybe happening?

Thanks.

Best regards,
Rajesh

**Comment by lauraluebbert** [comment]
Hi Rajesh, thank you for reaching out. 

Could you please move this issue to the [kallisto repository](https://github.com/pachterlab/kallisto) and tell us a bit more about what you did (provide the exact commands that were run and the kallisto version)?

Best,

Laura

**Comment by Rajesh-HKU** [comment]
Dear Laura,

Thanks for your response. The details are as follows:

Software versions:
Kb_python 0.28.2
Kallisto 0.48

Count Matrix Commands:
The code reads a list of fastq files and creates a count matrix of either genes or tcc associated with each specimen and saves the file with the specimen prefix.

Gene count matrix :

  1.
system(paste("kb count -i index.idx -g t2g.txt -x 10xv2 -t 2  --overwrite",    paste(fastq_fns[(2*i-1):(2*i)], collapse = " "), sep = " "), intern = TRUE)
  2.
 my_files <- list.files(path = "./counts_unfiltered",pattern = "^cells_x_genes")
  3.
file.copy(from = paste0("./counts_unfiltered/", my_files),  to = paste0("./cell_out/unfcounts/",specimens[2*i],"_", my_files))

Tcc_count matrix:

  1.
system(paste("kb count -i index.idx -g t2g.txt -x 10xv2 -t2 --tcc --overwrite", paste(fastq_fns[(2*i-1):(2*i)], collapse = " "), sep = " "), intern = TRUE)
  2.
my_files <- list.files(path = "./counts_unfiltered",pattern = "^cells_x_tcc")
  3.
file.copy(from = paste0("./counts_unfiltered/", my_files),           to=paste0("./cell_out/unfcounts_tcc/",specimendata$specimenID[i],"_", my_files))

For the purpose of comparison of a particular gene vs tcc count, we only included the equivalent classes which had one gene mapping only.

#read the gene count matrix and identify rows in the gene count matrix matching to BIN1 gene

  1.
lib <-  lib <- specimendata$specimenID[i]
  2.
count_file <- paste0(lib,"_cells_x_genes")
  3.
rowbin1 <- which(grepl(pattern = "^ENSG00000136717",rownames(res_matx))) #row 7729
  4.
res_mat <- read_count_output(dir = "./cell_out/unfcounts_tcc/",   name = count_file, tcc = TRUE)
  5.
totalgene <- res_mat[rowbin1_tcc,]


#read the tcc count matrix, identify rows in the t2g file matching BIN1 and use only those rows for counting BIN1 transcripts

  1.
lib <-  lib <- specimendata$specimenID[i]
  2.
count_file <- paste0(lib,"_cells_x_tcc")
  3.
rowbin1_tcc <- which(grepl(pattern = "\\tBIN1$",t2g$V1))  #rows 28581 to 28594
  4.
res_mat <- read_count_output(dir = "./cell_out/unfcounts_tcc/",   name = count_file, tcc = TRUE)
  5.
res_matx_tcc <- res_mat[rowbin1_tcc,]
  6.
#find total of 14 BIN1 transcripts for each cell
  7.
totalbin1 <- colSums(as.matrix(res_matx_tcc))


#compare res_matx and res_matx_tcc

table(totalgene,totalbin1)

      totalbin1 (sum of count of 14 transcripts)
            
            0           1     2         3    4    5    6

0               6877  933  151   29   15    1    0


1           1164  174   30    6    1    0    0

2           182   32    3    0    0    0    1

3           26    3    0    1    0    0    0

4           3    0    0    0    0    0    0

   
Please note above that when total of transcripts is >=1, the gene count is still predominantly zero.

Thanks.

Best regards,
Rajesh

________________________________
